# **Scraping Ulasan Game HayDay — Google Play Store**
Mengambil ulasan aplikasi HayDay dari Google Play Store menggunakanlibrary google-play-scraper dengan filter bahasa Indonesia.Target: 12.000 ulasan terbaru.

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.5 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
from google_play_scraper import reviews, Sort
import pandas as pd

# scraping review hayday dari play store
hasil, token = reviews(
    'com.supercell.hayday',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=12000
)

df = pd.DataFrame(hasil)
print(len(df), "review terkumpul")
df.head()

12000 review terkumpul

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,838c86e4-9600-4897-be9e-01c424dc1423,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"game hayday sy sdh 1mng ga bs dibuka, hanya "" ...",3,0,None,2026-09-25 09:03:00,None,None,None
1,1f293b10-cdd5-44c8-abcf-2d151fab09ad,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,pembelian diamond koq ga masuk2 ya dr semalem ...,4,0,1.72.86,2026-09-25 08:21:28,None,None,1.72.86
2,3500fa6b-7230-4d22-80a2-b5118c751248,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,game masa kecilku ini perkembangannya semakin ...,5,0,None,2026-09-24 23:21:18,None,None,None
3,6c1d82d8-6ddc-45c3-b527-017337aa8cc1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Baguss gamenya,5,0,1.72.86,2026-09-24 19:05:11,None,None,1.72.86
4,f51e99fd-8595-42a8-bc2c-8bd5f5a69bb6,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,game nya seruuu .. betah banget mainnyaa .. 🥰🥰,5,0,1.72.86,2026-09-24 18:54:11,None,None,1.72.86

In [3]:
# ambil kolom yang dibutuhin
df = df[['userName', 'score', 'at', 'content']]

# buang review kosong dan duplikat
df = df.dropna(subset=['content'])
df = df.drop_duplicates(subset=['content'])
df = df.reset_index(drop=True)

print(len(df), "review setelah dibersihkan")
df['score'].value_counts().sort_index()

# simpan ke csv
df.to_csv('hayday_reviews.csv', index=False)
print("disimpan: hayday_reviews.csv")
df.head()

10148 review setelah dibersihkan
disimpan: hayday_reviews.csv

,userName,score,at,content
0,Pengguna Google,3,2026-09-25 09:03:00,"game hayday sy sdh 1mng ga bs dibuka, hanya "" ..."
1,Pengguna Google,4,2026-09-25 08:21:28,pembelian diamond koq ga masuk2 ya dr semalem ...
2,Pengguna Google,5,2026-09-24 23:21:18,game masa kecilku ini perkembangannya semakin ...
3,Pengguna Google,5,2026-09-24 19:05:11,Baguss gamenya
4,Pengguna Google,5,2026-09-24 18:54:11,game nya seruuu .. betah banget mainnyaa .. 🥰🥰